language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
install: composer install --prefer-source
before_script: php ./vendor/bin/phpcs --config-set installed_paths "`pwd`/vendor/socialengine/sniffer-rules/src/SocialEngine/SnifferRules/Standard/"
script:
  - make sniff
  - make test
